services:
  airport-db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airport
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
